- name: Deploy application with Docker Compose
  hosts: workers
  become: yes
  tasks:
   - name: Log into private registry and force re-authorization
      docker_login:
        registry: registry.e-crops.co
        username: "{{ registry_username }}"
        password: "{{ registry_password }}"
        reauthorize: yes
        
   - name: Install Docker Compose
     apt:
       name: docker-compose
       state: present
       
   - name: Make Directory
     shell: mkdir -p /opt/register-app

   - name: Copy Docker Compose file
     copy:
       src: ./register-app/docker-compose.yml
       dest: /opt/register-app/docker-compose.yml

   - name: Start Docker Compose
     command: docker-compose up -d
     args:
       chdir: /opt/register-app
