- name: Git
  hosts: workers
  vars:
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
    git_user: leangsengk90
    git_pass: uzrjPlbFWc8l3qXOTUTM0t4f3cwcgE1Zu9HJ
  tasks:
    - name: Clone resource
      git:
        repo: "https://{{git_user|urlencode()}}:ghp_{{git_pass|urlencode()}}@github.com/leangsengk90/spring-register-test.git"
        dest: "/tmp/spring"
        version: master
