- name: Git
  hosts: localhost
  tasks:
    - name: Clone resource
      git:
        repo: "https://github.com/leangsengk90/spring-register-test.git"
        dest: ./
        version: "master"
        credentials:
          username: "leangsengk90"
          password: "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"
       
