- name: Git
  hosts: localhost
  vars:
    username: leangsengk90
    token: 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
  tasks:
    - name: Clone resource
      git:
        repo: 'https://{{ token }}@github.com/leangsengk90/spring-register-test.git'
        dest: ./
        version: "master"
