- name: Git
  hosts: localhost
  tasks:
    - name: Clone resource 
      uri: 
        url: "https://github.com/leangsengk90/spring-register-test.git"
        method: git
        dest: ./
        username: "leangsengk90"
        password: "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"
       
