- name: Git
  hosts: localhost
  vars:
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
  tasks:
    - name: Clone resource
      git:
        url: 'https://github.com/leangsengk90/spring-register-test.git'
        credentials: 'github-token'
