- name: Git
  hosts: workers
  vars:
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
  tasks:
    - name: Clone resource
      git:
        repo: 'https://github.com/leangsengk90/spring-register-test.git'
        dest: /home/$USER/springs
        version: master
        key_file: jenkins-private-key
