- name: Git
  hosts: workers
  vars:
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
    git_user: leangsengk90
    git_pass: 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
  tasks:
    - name: Clone resource
      git:
        repo: "https://{{git_user|urlencode()}}:{{git_pass|urlencode()}}@github.com/leangsengk90/spring-register-test.git"
        dest: "/tmp/spring"
        update: yes
