pipeline{
  agent { label 'master'}
  stages{
    stage("Git Clone Resource"){
      steps{
        ansiblePlaybook(
          inventory: 'inventory',
          playbook: 'gitclone-playbook.yml'
        ) 
      }
    }
  }
}
