pipeline{
  agent { label 'master'}
  tools{
    maven "3.6.3" 
  }
  stages{
    stage("Git Clone Resource"){
      steps{
        ansiblePlaybook(
          inventory: 'inventory',
          playbook: 'gitclone-playbook.yml'
        ) 
      }
    }

    stage("Build Image and Push to Registry"){
      steps{
        dir("register-app"){
          sh "mvn clean package"
        }
        sh """
            ansible-playbook docker-image-playbook.yml \
            -i inventory \
            -e registry_username=dara \
            -e registry_password=123
        """
      }
    }
  }
}
